from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID

from domain.models.activity_log import ActivityLog
from domain.models.brand import Brand, BrandMember
from domain.models.contract import Contract
from domain.models.creator import Creator, GrowthSnapshot
from domain.models.deal import Deal
from domain.models.deliverable import Deliverable
from domain.models.message import Message
from domain.models.negotiation import (
    ChecklistState,
    NegotiationConversation,
    NegotiationOffer,
    NegotiationSession,
)
from domain.models.payment import Payment


@runtime_checkable
class BrandRepo(Protocol):
    async def create(self, brand: Brand) -> Brand: ...
    async def get(self, id: UUID) -> Brand | None: ...

@runtime_checkable
class BrandMemberRepo(Protocol):
    async def create(self, member: BrandMember) -> BrandMember: ...
    async def list_for_brand(self, brand_id: UUID) -> list[BrandMember]: ...
    async def get_by_user_id(self, user_id: UUID) -> BrandMember | None: ...

@runtime_checkable
class CreatorRepo(Protocol):
    async def create(self, creator: Creator) -> Creator: ...
    async def get(self, id: UUID) -> Creator | None: ...
    async def list_for_brand(self, brand_id: UUID, limit: int = 50, offset: int = 0) -> list[Creator]: ...
    async def get_by_user_id(self, user_id: UUID) -> Creator | None: ...
    async def update_profile(
        self, id: UUID, followers_count: int, engagement_rate: float,
        avg_views_per_week: int | None = None,
    ) -> Creator: ...
    async def link_brand(self, creator_id: UUID, brand_id: UUID) -> None: ...
    async def is_linked_to_brand(self, creator_id: UUID, brand_id: UUID) -> bool: ...
    async def list_linked_brands(self, creator_id: UUID) -> list[Brand]: ...

@runtime_checkable
class GrowthSnapshotRepo(Protocol):
    async def create(self, snapshot: GrowthSnapshot) -> GrowthSnapshot: ...
    async def list_for_creator(self, creator_id: UUID, limit: int = 60) -> list[GrowthSnapshot]: ...

@runtime_checkable
class DealRepo(Protocol):
    async def create(self, deal: Deal) -> Deal: ...
    async def get(self, id: UUID) -> Deal | None: ...
    async def list_for_brand(self, brand_id: UUID, limit: int = 50, offset: int = 0) -> list[Deal]: ...
    async def list_for_creator(self, creator_id: UUID, limit: int = 50, offset: int = 0) -> list[Deal]: ...
    async def update_status(self, id: UUID, status: str) -> Deal: ...
    async def mark_viewed(self, id: UUID) -> Deal: ...

@runtime_checkable
class ContractRepo(Protocol):
    async def create(self, contract: Contract) -> Contract: ...
    async def get(self, id: UUID) -> Contract | None: ...
    async def list_for_brand(self, brand_id: UUID, limit: int = 50, offset: int = 0) -> list[Contract]: ...
    async def list_for_creator(self, creator_id: UUID, limit: int = 50, offset: int = 0) -> list[Contract]: ...
    async def update_status(self, id: UUID, status: str) -> Contract: ...
    async def update_status_and_previous(self, id: UUID, status: str, previous_status: str | None) -> Contract: ...
    async def update_creator_status(self, id: UUID, creator_status: str) -> Contract: ...
    async def update_raw_text(self, id: UUID, raw_text: str) -> Contract: ...

@runtime_checkable
class DeliverableRepo(Protocol):
    async def create(self, deliverable: Deliverable) -> Deliverable: ...
    async def get(self, id: UUID) -> Deliverable | None: ...
    async def list_for_brand(self, brand_id: UUID, limit: int = 50, offset: int = 0) -> list[Deliverable]: ...
    async def list_for_creator(self, creator_id: UUID, limit: int = 50, offset: int = 0) -> list[Deliverable]: ...
    async def update_status(self, id: UUID, status: str) -> Deliverable: ...

@runtime_checkable
class ActivityLogRepo(Protocol):
    async def create(self, log: ActivityLog) -> ActivityLog: ...
    async def get(self, id: UUID) -> ActivityLog | None: ...
    async def list_for_brand(self, brand_id: UUID, limit: int = 50, offset: int = 0) -> list[ActivityLog]: ...
    async def list_for_deal(self, deal_id: UUID, limit: int = 50, offset: int = 0) -> list[ActivityLog]: ...
    async def list_for_creator(self, creator_id: UUID, limit: int = 50, offset: int = 0) -> list[ActivityLog]: ...

@runtime_checkable
class PaymentRepo(Protocol):
    async def create(self, payment: Payment) -> Payment: ...
    async def get(self, id: UUID) -> Payment | None: ...
    async def list_for_brand(self, brand_id: UUID, limit: int = 50, offset: int = 0) -> list[Payment]: ...
    async def list_for_creator(self, creator_id: UUID, limit: int = 50, offset: int = 0) -> list[Payment]: ...
    async def mark_paid(self, id: UUID, invoice_number: str | None = None) -> Payment: ...
    async def update_status(self, id: UUID, status: str) -> Payment: ...

@runtime_checkable
class NegotiationSessionRepo(Protocol):
    async def create(self, session: NegotiationSession) -> NegotiationSession: ...
    async def get(self, id: UUID) -> NegotiationSession | None: ...
    async def list_for_brand(self, brand_id: UUID, limit: int = 50, offset: int = 0) -> list[NegotiationSession]: ...
    async def list_for_creator(self, creator_id: UUID, limit: int = 50, offset: int = 0) -> list[NegotiationSession]: ...
    async def update_checklist(self, id: UUID, checklist: ChecklistState) -> NegotiationSession: ...
    async def save_offer(self, offer: NegotiationOffer) -> NegotiationOffer: ...
    async def list_offers(self, session_id: UUID) -> list[NegotiationOffer]: ...

@runtime_checkable
class NegotiationConversationRepo(Protocol):
    async def create(self, conversation: NegotiationConversation) -> NegotiationConversation: ...
    async def list_for_session(self, session_id: UUID) -> list[NegotiationConversation]: ...

@runtime_checkable
class ClauseCardRepo(Protocol):
    async def create(self, card: ClauseCardOut) -> ClauseCardOut: ...
    async def get(self, id: UUID) -> ClauseCardOut | None: ...
    async def list_for_contract(self, contract_id: UUID) -> list[ClauseCardOut]: ...
    async def update(self, card: ClauseCardOut) -> ClauseCardOut: ...
    async def list_for_brand(self, brand_id: UUID) -> list[ClauseCardOut]: ...


@runtime_checkable
class EscalationRepo(Protocol):
    async def create(self, escalation: EscalationOut) -> EscalationOut: ...
    async def get(self, id: UUID) -> EscalationOut | None: ...
    async def get_open_for_contract(self, contract_id: UUID) -> list[EscalationOut]: ...
    async def resolve(self, id: UUID, status: str, resolved_by: UUID, note: str) -> EscalationOut: ...
    async def list_for_brand(self, brand_id: UUID) -> list[EscalationOut]: ...

@runtime_checkable
class RateBenchmarkRepo(Protocol):
    async def get_historical_rates(self, niche: str, follower_tier: str) -> list[float]: ...

@runtime_checkable
class MessageRepo(Protocol):
    async def create(self, message: Message) -> Message: ...
    async def list_for_thread(self, brand_id: UUID, creator_id: UUID, limit: int = 200) -> list[Message]: ...

