/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/brand/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Brand Signup */
        post: operations["brand_signup_auth_brand_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/brand/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Brand Login */
        post: operations["brand_login_auth_brand_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/creator/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creator Signup */
        post: operations["creator_signup_auth_creator_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/creator/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creator Login */
        post: operations["creator_login_auth_creator_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creators */
        get: operations["list_creators_creators_get"];
        put?: never;
        /** Onboard Creator */
        post: operations["onboard_creator_creators_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile_creators_me_patch"];
        trace?: never;
    };
    "/creators/me/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Brands */
        get: operations["list_my_brands_creators_me_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/me/link-brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Brand */
        post: operations["link_brand_creators_me_link_brand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Creator */
        get: operations["get_creator_creators__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deals */
        get: operations["list_deals_deals_get"];
        put?: never;
        /** Create Deal */
        post: operations["create_deal_deals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/weekly-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly Completed Value */
        get: operations["weekly_completed_value_deals_weekly_value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Deal Status */
        patch: operations["update_deal_status_deals__id__status_patch"];
        trace?: never;
    };
    "/deals/{deal_id}/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Contract */
        post: operations["upload_contract_deals__deal_id__contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creators/me/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Personal Contract */
        post: operations["upload_personal_contract_creators_me_contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_contracts__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contracts */
        get: operations["list_contracts_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Contract Status */
        patch: operations["update_contract_status_contracts__id__status_patch"];
        trace?: never;
    };
    "/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deliverables */
        get: operations["list_deliverables_deliverables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{deal_id}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Deliverable */
        post: operations["create_deliverable_deals__deal_id__deliverables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliverables/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Deliverable Status */
        patch: operations["update_deliverable_status_deliverables__id__status_patch"];
        trace?: never;
    };
    "/activity-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Logs */
        get: operations["get_activity_logs_activity_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiation/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_negotiation_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_negotiation_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiation/sessions/{id}/rate-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rate Range */
        get: operations["get_rate_range_negotiation_sessions__id__rate_range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiation/sessions/{id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_negotiation_sessions__id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiation/sessions/{id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Checklist */
        patch: operations["update_checklist_negotiation_sessions__id__checklist_patch"];
        trace?: never;
    };
    "/negotiation/sessions/{id}/counter-offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Counter Offer */
        post: operations["create_counter_offer_negotiation_sessions__id__counter_offer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiation/sessions/{id}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Offers */
        get: operations["list_offers_negotiation_sessions__id__offers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiation/sessions/{id}/script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Script */
        post: operations["generate_script_negotiation_sessions__id__script_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Payments */
        get: operations["list_payments_payments_get"];
        put?: never;
        /** Create Payment */
        post: operations["create_payment_payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{contract_id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Paid */
        patch: operations["mark_paid_payments__contract_id__mark_paid_patch"];
        trace?: never;
    };
    "/payments/{contract_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Payment Status */
        patch: operations["update_payment_status_payments__contract_id__status_patch"];
        trace?: never;
    };
    "/contracts/{contract_id}/clauses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clauses */
        get: operations["get_clauses_contracts__contract_id__clauses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Contract */
        post: operations["scan_contract_contracts__contract_id__scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate Clause */
        post: operations["escalate_clause_contracts__contract_id__escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escalations/{escalation_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Escalation */
        post: operations["resolve_escalation_escalations__escalation_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Benchmarks */
        get: operations["get_benchmarks_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brand Analytics */
        get: operations["get_brand_analytics_analytics_brand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityLog */
        ActivityLog: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Brand Id
             * Format: uuid
             */
            brand_id: string;
            /** Deal Id */
            deal_id?: string | null;
            /** Actor Type */
            actor_type: string;
            /** Actor Label */
            actor_label: string;
            /** Action */
            action: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuthSession */
        AuthSession: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "brand" | "creator";
            /** Brand Id */
            brand_id?: string | null;
            /** Brand Name */
            brand_name?: string | null;
            /** Creator Id */
            creator_id?: string | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** BenchmarkOut */
        BenchmarkOut: {
            /**
             * Insufficient Data
             * @default false
             */
            insufficient_data: boolean;
            /** P25 Rate */
            p25_rate?: number | null;
            /** P50 Rate */
            p50_rate?: number | null;
            /** P75 Rate */
            p75_rate?: number | null;
            /** Sample Size */
            sample_size?: number | null;
        };
        /** Body_upload_contract_deals__deal_id__contracts_post */
        Body_upload_contract_deals__deal_id__contracts_post: {
            /** File */
            file: string;
        };
        /** Body_upload_personal_contract_creators_me_contracts_post */
        Body_upload_personal_contract_creators_me_contracts_post: {
            /** File */
            file: string;
        };
        /** Brand */
        Brand: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Gst Number */
            gst_number?: string | null;
            /** Pan Number */
            pan_number?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BrandAnalytics */
        BrandAnalytics: {
            /** Total Creators */
            total_creators: number;
            /** Total Deals */
            total_deals: number;
            /** Deals By Status */
            deals_by_status: {
                [key: string]: number;
            };
            /** Revenue By Month */
            revenue_by_month: components["schemas"]["RevenueMonth"][];
            /** Top Brands */
            top_brands: components["schemas"]["TopBrand"][];
            /** Creator Performance */
            creator_performance: components["schemas"]["CreatorPerformance"][];
            contract_risk: components["schemas"]["ContractRiskStats"];
            negotiation_stats: components["schemas"]["NegotiationStats"];
            /** Overdue Payments Count */
            overdue_payments_count: number;
            /** Overdue Payments Total */
            overdue_payments_total: number;
            /** Roster By Niche */
            roster_by_niche: components["schemas"]["NicheBreakdown"][];
        };
        /** BrandLoginRequest */
        BrandLoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** BrandSignupRequest */
        BrandSignupRequest: {
            /** Brand Name */
            brand_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ChecklistState */
        ChecklistState: {
            /**
             * Usage Rights Duration Set
             * @default false
             */
            usage_rights_duration_set: boolean;
            /**
             * Exclusivity Scope Set
             * @default false
             */
            exclusivity_scope_set: boolean;
            /**
             * Revision Limit Set
             * @default false
             */
            revision_limit_set: boolean;
            /**
             * Payment Timeline Set
             * @default false
             */
            payment_timeline_set: boolean;
        };
        /** ClauseCardOut */
        ClauseCardOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Clause Type */
            clause_type: string;
            /** Raw Text */
            raw_text: string;
            /**
             * Flag
             * @enum {string}
             */
            flag: "red" | "yellow" | "green";
            /** Flag Reason Code */
            flag_reason_code?: string | null;
            /** Llm Explanation */
            llm_explanation?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ClauseInput */
        ClauseInput: {
            /** Clause Type */
            clause_type: string;
            /** Raw Text */
            raw_text: string;
        };
        /** Contract */
        Contract: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Deal Id */
            deal_id?: string | null;
            /** Creator Id */
            creator_id?: string | null;
            /** File Path */
            file_path?: string | null;
            /** Status */
            status: string;
            /** Usage Rights Duration Days */
            usage_rights_duration_days?: number | null;
            /** Exclusivity Scope */
            exclusivity_scope?: string | null;
            /** Revision Limit */
            revision_limit?: number | null;
            /** Payment Timeline Days */
            payment_timeline_days?: number | null;
            /** Previous Status */
            previous_status?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ContractRiskStats */
        ContractRiskStats: {
            /** Contracts Scanned */
            contracts_scanned: number;
            /** Clauses Reviewed */
            clauses_reviewed: number;
            /** Red Flags */
            red_flags: number;
            /** Yellow Flags */
            yellow_flags: number;
            /** Green Flags */
            green_flags: number;
            /** Open Escalations */
            open_escalations: number;
            /** Resolved Escalations */
            resolved_escalations: number;
        };
        /** ContractStatusUpdateRequest */
        ContractStatusUpdateRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "uploaded" | "signed" | "void";
        };
        /** CounterOfferRequest */
        CounterOfferRequest: {
            /** Amount */
            amount: number;
            /** Message */
            message?: string | null;
        };
        /** Creator */
        Creator: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Brand Id */
            brand_id?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Display Name */
            display_name: string;
            /** Instagram Handle */
            instagram_handle: string;
            /** Niche */
            niche: string;
            /** Follower Tier */
            follower_tier: string;
            /** Followers Count */
            followers_count?: number | null;
            /** Engagement Rate */
            engagement_rate?: number | null;
            /** Avg Views Per Week */
            avg_views_per_week?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CreatorLoginRequest */
        CreatorLoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** CreatorOnboardRequest */
        CreatorOnboardRequest: {
            /** Display Name */
            display_name: string;
            /** Instagram Handle */
            instagram_handle: string;
            /** Niche */
            niche: string;
            /** Follower Tier */
            follower_tier: string;
            /** Followers Count */
            followers_count?: number | null;
            /** Engagement Rate */
            engagement_rate?: number | null;
            /** Avg Views Per Week */
            avg_views_per_week?: number | null;
        };
        /** CreatorPerformance */
        CreatorPerformance: {
            /**
             * Creator Id
             * Format: uuid
             */
            creator_id: string;
            /** Display Name */
            display_name: string;
            /** Niche */
            niche: string;
            /** Follower Tier */
            follower_tier: string;
            /** Deal Count */
            deal_count: number;
            /** Total Value */
            total_value: number;
        };
        /** CreatorProfileUpdateRequest */
        CreatorProfileUpdateRequest: {
            /** Followers Count */
            followers_count: number;
            /** Engagement Rate */
            engagement_rate: number;
            /** Avg Views Per Week */
            avg_views_per_week?: number | null;
        };
        /** CreatorSignupRequest */
        CreatorSignupRequest: {
            /** Display Name */
            display_name: string;
            /** Instagram Handle */
            instagram_handle: string;
            /** Niche */
            niche: string;
            /** Follower Tier */
            follower_tier: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Deal */
        Deal: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Brand Id
             * Format: uuid
             */
            brand_id: string;
            /**
             * Creator Id
             * Format: uuid
             */
            creator_id: string;
            /** Campaign Name */
            campaign_name: string;
            /** Contact Email */
            contact_email: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DealCreateRequest */
        DealCreateRequest: {
            /**
             * Creator Id
             * Format: uuid
             */
            creator_id: string;
            /** Campaign Name */
            campaign_name: string;
            /** Contact Email */
            contact_email: string;
            /** Brand Id */
            brand_id?: string | null;
        };
        /** DealStatusUpdateRequest */
        DealStatusUpdateRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "lead" | "negotiating" | "contracted" | "in_production" | "completed" | "cancelled";
        };
        /** Deliverable */
        Deliverable: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Deal Id
             * Format: uuid
             */
            deal_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** File Path */
            file_path?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DeliverableCreateRequest */
        DeliverableCreateRequest: {
            /**
             * Deal Id
             * Format: uuid
             */
            deal_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
        /** DeliverableStatusUpdateRequest */
        DeliverableStatusUpdateRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "in_production" | "editing" | "submitted" | "approved" | "rejected" | "revision_requested";
            /** Note */
            note?: string | null;
        };
        /** EscalateRequest */
        EscalateRequest: {
            /**
             * Clause Card Id
             * Format: uuid
             */
            clause_card_id: string;
            /** Reason Code */
            reason_code: string;
        };
        /** EscalationOut */
        EscalationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /**
             * Clause Card Id
             * Format: uuid
             */
            clause_card_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "cleared" | "amended" | "rejected";
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved By */
            resolved_by?: string | null;
            /** Resolution Note */
            resolution_note?: string | null;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /** Week */
            week: number;
            /** Low */
            low: number;
            /** Mid */
            mid: number;
            /** High */
            high: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinkBrandRequest */
        LinkBrandRequest: {
            /** Invite Code */
            invite_code: string;
        };
        /** NegotiationOffer */
        NegotiationOffer: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Amount */
            amount: number;
            /** Message */
            message?: string | null;
            /**
             * Sender
             * @enum {string}
             */
            sender: "creator" | "brand";
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /** NegotiationSession */
        NegotiationSession: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Deal Id
             * Format: uuid
             */
            deal_id: string;
            /** Status */
            status: string;
            /** Views Per Week */
            views_per_week: number;
            /** Niche Cpm */
            niche_cpm: number;
            /** Follower Tier Multiplier */
            follower_tier_multiplier: number;
            /** Engagement Rate Adjustment */
            engagement_rate_adjustment: number;
            /** Base Rate */
            base_rate: number;
            /** Range Low */
            range_low: number;
            /** Range High */
            range_high: number;
            checklist: components["schemas"]["ChecklistState"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NegotiationSessionCreate */
        NegotiationSessionCreate: {
            /**
             * Deal Id
             * Format: uuid
             */
            deal_id: string;
            /** Views Per Week */
            views_per_week: number;
            /** Niche Cpm */
            niche_cpm: number;
            /** Follower Tier Multiplier */
            follower_tier_multiplier: number;
            /** Engagement Rate Adjustment */
            engagement_rate_adjustment: number;
        };
        /** NegotiationStats */
        NegotiationStats: {
            /** Active Sessions */
            active_sessions: number;
            /** Avg Base Rate */
            avg_base_rate: number;
            /** Avg Ask */
            avg_ask: number;
            /** Avg Brand Offer */
            avg_brand_offer: number;
        };
        /** NicheBreakdown */
        NicheBreakdown: {
            /** Niche */
            niche: string;
            /** Follower Tier */
            follower_tier: string;
            /** Creator Count */
            creator_count: number;
            /** Avg Engagement Rate */
            avg_engagement_rate?: number | null;
        };
        /** Payment */
        Payment: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Amount Inr */
            amount_inr: string;
            /** Status */
            status: string;
            /** Invoice Number */
            invoice_number: string;
            /** Invoice Pdf Path */
            invoice_pdf_path?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Paid At */
            paid_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PaymentCreateRequest */
        PaymentCreateRequest: {
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Amount Inr */
            amount_inr: number | string;
            /** Due Date */
            due_date?: string | null;
        };
        /** PaymentStatusUpdateRequest */
        PaymentStatusUpdateRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "paid" | "overdue";
        };
        /** RateRangeOut */
        RateRangeOut: {
            /** Base Rate */
            base_rate: number;
            /** Range Low */
            range_low: number;
            /** Range High */
            range_high: number;
        };
        /** ResolveEscalationRequest */
        ResolveEscalationRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "cleared" | "amended" | "rejected";
            /** Note */
            note: string;
        };
        /** RevenueMonth */
        RevenueMonth: {
            /** Month */
            month: string;
            /** Paid */
            paid: number;
            /** Pending */
            pending: number;
        };
        /** ScanContractRequest */
        ScanContractRequest: {
            /** Clauses */
            clauses: components["schemas"]["ClauseInput"][];
        };
        /** ScriptGenerateRequest */
        ScriptGenerateRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Kind */
            kind: string;
            /**
             * Use Llm
             * @default true
             */
            use_llm: boolean;
        };
        /** TopBrand */
        TopBrand: {
            /** Campaign Name */
            campaign_name: string;
            /** Deal Count */
            deal_count: number;
            /** Total Value */
            total_value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyValuePoint */
        WeeklyValuePoint: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    brand_signup_auth_brand_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandSignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_login_auth_brand_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_signup_auth_creator_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatorSignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_login_auth_creator_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatorLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_creators_creators_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboard_creator_creators_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatorOnboardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_my_profile_creators_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatorProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_brands_creators_me_brands_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_brand_creators_me_link_brand_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkBrandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_creator_creators__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deals_deals_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deal_deals_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_completed_value_deals_weekly_value_get: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyValuePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deal_status_deals__id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_contract_deals__deal_id__contracts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_contract_deals__deal_id__contracts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_personal_contract_creators_me_contracts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_personal_contract_creators_me_contracts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_contracts__id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contracts_contracts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contract_status_contracts__id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deliverables_deliverables_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deliverable_deals__deal_id__deliverables_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliverableCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deliverable_status_deliverables__id__status_patch: {
        parameters: {
            query: {
                deal_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliverableStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_logs_activity_log_get: {
        parameters: {
            query?: {
                deal_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLog"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_negotiation_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationSession"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_negotiation_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NegotiationSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rate_range_negotiation_sessions__id__rate_range_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateRangeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_negotiation_sessions__id__forecast_get: {
        parameters: {
            query?: {
                weekly_growth_rate?: number;
                weeks?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_checklist_negotiation_sessions__id__checklist_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistState"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_counter_offer_negotiation_sessions__id__counter_offer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterOfferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationOffer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_offers_negotiation_sessions__id__offers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationOffer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_script_negotiation_sessions__id__script_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payments_payments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_payment_payments_post: {
        parameters: {
            query: {
                deal_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_paid_payments__contract_id__mark_paid_patch: {
        parameters: {
            query: {
                payment_id: string;
                deal_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_payment_status_payments__contract_id__status_patch: {
        parameters: {
            query: {
                payment_id: string;
                deal_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clauses_contracts__contract_id__clauses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClauseCardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_contract_contracts__contract_id__scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanContractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClauseCardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_clause_contracts__contract_id__escalate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_escalation_escalations__escalation_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                escalation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveEscalationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_benchmarks_benchmarks_get: {
        parameters: {
            query: {
                niche: string;
                follower_tier: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_analytics_analytics_brand_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandAnalytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
